apiVersion: v1
kind: ConfigMap
metadata:
  name: pvz-backend-config
data:
  GAME_URL: https://staging-pvz.obivan.org
  BACKEND_URL: https://staging-pvz.obivan.org
  ALLOWED_ORIGINS: https://staging-pvz.obivan.org
  CORS_ENABLED: "true"
  USE_GITHUB_AUTH: "false"
  USE_TURNSTILE: "false"
  USE_OPENAI_MODERATION: "false"
  USE_REPORTING: "false"
  USE_UPLOAD_LOGGING: "false"
  DISCORD_PROVIDER_ENABLED: "false"
  BLUESKY_PROVIDER_ENABLED: "false"
  USE_POSTHOG_ANALYTICS: "false"
