apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pvz-staging

resources:
  - ../../base
  - namespace.yaml
  - game-config.yaml
  - backend-config.yaml
  - secrets/ghcr-pull.sops.yaml

images:
  - name: ghcr.io/0b-ivan/pvz-game
    newName: ghcr.io/0b-ivan/pvz-game
    digest: sha256:082ee0cdde80f7477de29522e33573971b74af3769308d80371bc77ffbf67f90
  - name: ghcr.io/0b-ivan/pvz-backend
    newName: ghcr.io/0b-ivan/pvz-backend
    digest: sha256:81bb473de4ce31a2a2fdd34eb95f8e817fe47daea7a943eacb97371505bb5642

replicas:
  - name: pvz-game
    count: 1
  - name: pvz-backend
    count: 1

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ghcr-pull
