apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: pvz-staging
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:pRtgIjDguSjTOFeCQg3Y9QvGBx/5+869dBmHOnKFzJbhpeyMOfonoRe1VYLpOARBU64Gq6QgmQeq//eVbD+xlAT8bYfuYtoHANuQYu9FRTqrz2mzFcaYnMFH/a3BMRFNrcDKSo5pb09sxFta09c1/zCH9pike3TYT/AD+r5Q0neWX+GuFDiY2zo9LkjL7ZF0dLC09es/d9JXBBwIcIuM60c+0DuaIFu6DVj6jo4c0XG2cV2cIbaQMGncPAMcILG71lj+FSXogc5Lf+dy/H3fctYO52fiulWavrHntavLk7AZePdwuggB+g==,iv:v+Np/RKjYIMpQcJ2aV4Ebh3zDhg4iXbQrrWSXqiKBSw=,tag:pplj4YskRQMpyaAOWEuS2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRG9Vay83bTZ1LzFpaE9F
            dFVFZUZWMjdwYkx0Vm8wTmMwazk4Z2lmdlFJCjdidHdsSmppMERtaW5qblRIL1kr
            TTRya1lTRmg3WGhYNXRwU1pJWEtEUW8KLS0tIDdXaU9UeitvWjhiUUFhYlM3Mmhl
            OE50WG9CeFk1NkJiVHRFSUJ0Z1lTaDQKiQ2393wzXLojg4m22Jsy7Ku37/YMJZ6N
            Eia6ibB44IezEVQsP90IA9bywjeJuFs0ur1g+NsSrEFXegJhpY3P1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18k59jeka6qm0nkm8ckl4wd52z3v8l4wmqshshkj44qe7ylacqqysav9zj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T11:57:00Z"
    mac: ENC[AES256_GCM,data:Ev7U8J5AtFVWsacxbFBdMC8QXLQgRIJpXucJaMssPnOYmoH+OuoIUOhkEoGsbr9IgTRQX7/kYgIANgfFkCuWgGZMMqLfoxxYicfblcpUncLrl6jE/xt40Pog00HyzML3MgjXcl2JJRGbJx0afAdjxdoBuFmVBVgiM/zlx5xd/GY=,iv:kA9kjOFxFydfl1HyfZGkYcvypO1HZquMyc0HYqyRLd8=,tag:LDvZDmSrV9/ygmGdubhIrA==,type:str]
    version: 3.13.3
