apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvz-backend-data
  labels:
    app.kubernetes.io/name: pvz-backend
    app.kubernetes.io/part-of: pvz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
